name: Kubernetes Installation Test

on: 
  pull_request:
    paths:
    - 'kubernetes/**'
  push:
    branches:
    - master
    paths:
    - 'kubernetes/**'

jobs:
  kubernetes-installation-test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
    - name: Create Kind Cluster
      uses: helm/kind-action@7a937c0fb648064a83b8b9354151e5e543d9fcec # v1.1.0
    - name: Install Spilo
      run: kubectl apply -f kubernetes/spilo_kubernetes.yaml
